[[redirects]]
    from = "/*"
    to = "https://files.ari.lt/:splat"
    status = 301
    force = true

# Processing
[build.processing]
    skip_processing = true
# --------------

[[headers]]
    for = "/files.json"

    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET"

[[headers]]
    for = "/files_json_hash.txt"

    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET"

[[headers]]
    for = "/*"

    [headers.values]
        Strict-Transport-Security = "max-age=0"
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests"
        X-Permitted-Cross-Domain-Policies = "none"
        Referrer-Policy = "no-referrer"

