[build]
    command = "python3 scripts/tree.py"

[[redirects]]
    from = "/git"
    to = "https://ari-web.xyz/gh/files.ari-web.xyz"
    status = 308
    force = true

[[redirects]]
    from = "/favicon.ico"
    to = "https://ari-web.xyz/favicon.ico"
    status = 200
    force = true

[[redirects]]
    from = "/netlify.toml"
    to = "/404"
    status = 404
    force = true

[[redirects]]
    from = "/404"
    to = "https://ari-web.xyz/404.files.xyz"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "404"
    status = 404
    force = false

