[build]
    command = "python3 scripts/tree.py"

[[redirects]]
    from = "/*"
    to = "https://ari-web.xyz/404.files.xyz"
    status = 404
    force = false

[[redirects]]
    from = "/git"
    to = "https://ari-web.xyz/gh/files.ari-web.xyz"
    status = 404
    force = false

